site_name: Simulación Lavadero de Coches - Tarea Obligatoria 1
site_url: http://localhost:8000
site_description: Documentación del proyecto de simulación de un túnel de lavado de coches con tests unitarios.
site_author: Tu Nombre

docs_dir: docs

site_dir: site

nav:
  - Introducción: index.md
